[project]
name = "llm-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elasticsearch8>=8.18.1",
    "requests>=2.32.3",
    "tiktoken>=0.9.0",
    "tqdm>=4.67.1",
]
